// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import "package:firebase_core/firebase_core.dart";

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoirfPrWntcHwYNx5D5R5H5Wp75mxH7N4',
    appId: '1:949515363359:web:61e2dce558b047ba8ae12a',
    messagingSenderId: '949515363359',
    projectId: 'hello-world-db04f',
    authDomain: 'hello-world-db04f.firebaseapp.com',
    storageBucket: 'hello-world-db04f.firebasestorage.app',
    measurementId: 'G-RBZH11T3H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LT5bpzQ_2ru9nh97MD_WCRjhYFAOdGc',
    appId: '1:949515363359:android:1a925ee9f54203598ae12a',
    messagingSenderId: '949515363359',
    projectId: 'hello-world-db04f',
    storageBucket: 'hello-world-db04f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp_wh4WU-cyxrTJUkj1UT3cnQD_eQ4xds',
    appId: '1:949515363359:ios:d2eb64ab5f73a55e8ae12a',
    messagingSenderId: '949515363359',
    projectId: 'hello-world-db04f',
    storageBucket: 'hello-world-db04f.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp_wh4WU-cyxrTJUkj1UT3cnQD_eQ4xds',
    appId: '1:949515363359:ios:d2eb64ab5f73a55e8ae12a',
    messagingSenderId: '949515363359',
    projectId: 'hello-world-db04f',
    storageBucket: 'hello-world-db04f.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoirfPrWntcHwYNx5D5R5H5Wp75mxH7N4',
    appId: '1:949515363359:web:c5a85552daf551348ae12a',
    messagingSenderId: '949515363359',
    projectId: 'hello-world-db04f',
    authDomain: 'hello-world-db04f.firebaseapp.com',
    storageBucket: 'hello-world-db04f.firebasestorage.app',
    measurementId: 'G-M92XTC6FZN',
  );

}