// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import "package:firebase_core/firebase_core.dart";

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQign7mfW2KdzY3ChH_54z_sYAB12bxGk',
    appId: '1:304526874075:web:66a7a3af5c9ddaed2f43fe',
    messagingSenderId: '304526874075',
    projectId: 'helloworld-cef75',
    authDomain: 'helloworld-cef75.firebaseapp.com',
    storageBucket: 'helloworld-cef75.firebasestorage.app',
    measurementId: 'G-FQSZWC2DNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPV9un737BkFP5i3jt99P-5KSmtPSxYU',
    appId: '1:304526874075:android:cf1ba72add7d938a2f43fe',
    messagingSenderId: '304526874075',
    projectId: 'helloworld-cef75',
    storageBucket: 'helloworld-cef75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdWVQ8BIxR1_rOAwYFoznRWtyNN6lGibw',
    appId: '1:304526874075:ios:c120227541337d952f43fe',
    messagingSenderId: '304526874075',
    projectId: 'helloworld-cef75',
    storageBucket: 'helloworld-cef75.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdWVQ8BIxR1_rOAwYFoznRWtyNN6lGibw',
    appId: '1:304526874075:ios:c120227541337d952f43fe',
    messagingSenderId: '304526874075',
    projectId: 'helloworld-cef75',
    storageBucket: 'helloworld-cef75.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQign7mfW2KdzY3ChH_54z_sYAB12bxGk',
    appId: '1:304526874075:web:90ea917c9cf80d122f43fe',
    messagingSenderId: '304526874075',
    projectId: 'helloworld-cef75',
    authDomain: 'helloworld-cef75.firebaseapp.com',
    storageBucket: 'helloworld-cef75.firebasestorage.app',
    measurementId: 'G-KEXYSME5M7',
  );

}